# ANNO-Toolset, Maintainer: Konrad Höffner <konrad.hoeffner@imise.uni-leipzig.de>

services:

  jekyll:
    build:
      context: ./annosaxfdm.de
    volumes:
      - html:/html

  rickview:
    image: ghcr.io/konradhoeffner/rickview:master
    environment:
      - RICKVIEW_KB_FILE=https://github.com/annosaxfdm/ontology/releases/download/23.02.01/anno.ttl
      - RICKVIEW_PREFIX=anno
      - RICKVIEW_NAMESPACE=https://annosaxfdm.de/ontology/
      - RICKVIEW_BASE=/ontology
      - RICKVIEW_TITLE=ANNO
      - RICKVIEW_SUBTITLE=Anthropological Notation Ontology
      - RICKVIEW_EXAMPLES=Bone Anatomical_location Anatomical_plane Mandibula
      - RICKVIEW_HOMEPAGE=https://annosaxfdm.de
      - RICKVIEW_PORT=8101
      - RICKVIEW_LOG_LEVEL=debug
      - RICKVIEW_GITHUB=https://github.com/annosaxfdm/ontology
    volumes:
      - ./rickview.toml:/app/data/config.toml
    ports:
      - "127.0.0.1:8101:8101"
    restart: no

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - html:/html
    ports:
      - "0.0.0.0:8100:80"
    restart: unless-stopped

volumes:
  html:
