title_properties =  ["http://purl.org/dc/elements/1.1/title", "http://purl.org/dc/terms/title", "http://www.w3.org/2000/01/rdf-schema#label", "http://annosaxfdm.de/ontology/described_by_other_terms"]
type_properties = ["http://www.w3.org/1999/02/22-rdf-syntax-ns#type"]
description_properties = [ "http://www.w3.org/2004/02/skos/core#definition", "http://www.w3.org/2000/01/rdf-schema#comment", "http://annosaxfdm.de/ontology/definition"]
langs = ["en", "de", ""]
[namespaces]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
owl = "http://www.w3.org/2002/07/owl#"
xsd = "http://www.w3.org/2001/XMLSchema#"
vann = "http://purl.org/vocab/vann/"
sh = "http://www.w3.org/ns/shacl#"
skos = "http://www.w3.org/2004/02/skos/core#"
ov = "http://open.vocab.org/terms/"
dc = "http://purl.org/dc/elements/1.1/"
dct = "http://purl.org/dc/terms/"
dbr = "http://dbpedia.org/resource/"
fma = "http://purl.org/sig/ont/fma/"
dcat = "http://www.w3.org/ns/dcat#"
gfo = "http://www.onto-med.de/ontologies/gfo.owl#"
gfo-light = "https://w3id.org/gfo-light/"
